In [34]:
import numpy as np
import pandas as pd

In [25]:
def geraArray(numero, impar = True):
    
    end = False
    curr = 1 if impar else 0
    array = list()
    
    while end != True:
        if len(array) != numero:
            array.append(curr)
            curr += 2
        else:
            end = True
            
    return np.array(array)

In [48]:
a = pd.DataFrame({i:(geraArray(i).sum(),i**2) for i in np.arange(1,20000)}).T

In [49]:
a.rename(columns={0:'impares',1:'Real'})

         impares       Real
1              1          1
2              4          4
3              9          9
4             16         16
5             25         25
6             36         36
7             49         49
8             64         64
9             81         81
10           100        100
11           121        121
12           144        144
13           169        169
14           196        196
15           225        225
16           256        256
17           289        289
18           324        324
19           361        361
20           400        400
21           441        441
22           484        484
23           529        529
24           576        576
25           625        625
26           676        676
27           729        729
28           784        784
29           841        841
30           900        900
...          ...        ...
19970  398800900  398800900
19971  398840841  398840841
19972  398880784  398880784
19973  398920729  398920729
19974  398960676  398960676
19975  399000625  399000625
19976  399040576  399040576
19977  399080529  399080529
19978  399120484  399120484
19979  399160441  399160441
19980  399200400  399200400
19981  399240361  399240361
19982  399280324  399280324
19983  399320289  399320289
19984  399360256  399360256
19985  399400225  399400225
19986  399440196  399440196
19987  399480169  399480169
19988  399520144  399520144
19989  399560121  399560121
19990  399600100  399600100
19991  399640081  399640081
19992  399680064  399680064
19993  399720049  399720049
19994  399760036  399760036
19995  399800025  399800025
19996  399840016  399840016
19997  399880009  399880009
19998  399920004  399920004
19999  399960001  399960001

[19999 rows x 2 columns]